config/routes.rb
Rails.application.routes.draw do
  # require "sidekiq/web"
  # authenticate :user, ->(user) { user.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  devise_for :users
  #get '/search', to: 'pages#home', as: :search
  root to: 'pages#home'
 # root to: 'pages#splash'
  # get "/orders/:id/confirmation", to: "orders#confirmation", as: :order_confirmation
  delete "/offers", to: 'offers#destroy_all', as: :destroy_all
  get "/landing", to: 'pages#landing'
  resources :offers do
    resources :comments, only: [ :create ]
    resources :orders, only: [ :create ]
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  resources :businesses, only: [ :show, :new, :create, :edit, :update ]
  resources :orders, only: [ :index, :show, :destroy ] do
    get "/confirmation", to: "orders#confirmation"
    patch "/accept", to: "orders#accept"
    patch "/reject", to: "orders#reject"
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  skip_before_action :verify_business
  skip_before_action :authenticate_user!, only: [:show]
  skip_after_action :verify_authorized


  def show
    @business = Business.find(params[:id])
    if @business.geocoded?
      @marker = {
        lat: @business.latitude,
        lng: @business.longitude
      }
    end
  end

  def new
    @business = Business.new()
  end

  def create
    @business = Business.new(business_params)
    @business.user = current_user
    if @business.save
      redirect_to offers_path, notice: 'Your business was successfully created! '
    else
      render :new
    end
  end

  def edit
    @business = Business.find(current_user.business.id)
  end

  def update
    @business = Business.find(current_user.business.id)
    if @business.update(business_params)
      redirect_to business_path, notice: 'Your business was successfully updated'
    else
      render :new
    end
  end

  private
  def business_params
    params.require(:business).permit(:photo, :name, :description, :nickname, :address)
  end

end

app/views/businesses/_form.html.erb
<div class="container-form">

    <div class="row justify-content-center" style="margin-top: 2rem">
      <div class="d-flex justify-content-center">
        <% if @business.photo.key %>
          <%= cl_image_tag @business.photo.key, class: "avatar-xxl" %>
        <% else %>
          <%= image_tag "avatar.jpg", class:"avatar-xxl"%>
        <% end %>
      </div>
        <h3 class="d-flex justify-content-center" style="font-weight: bold">@<%= @business.nickname %></h3>
    </div>

    <div class="row justify-content-center" style="margin-top: 2rem">
      <div class="col-lg-6 col-sm-9 breath">
          <%= simple_form_for @business do |f| %>
            <%= f.input :name,
                  required: true,
                  autofocus: true,
                  hint: 'What is your business name?',
                  label: 'Business name' %>
              <%= f.input :nickname,
                  required: true,
                  autofocus: true,
                  hint: 'Select a unique nickname :)',
                  label: 'What will be your business nickname?'%>
              <%= f.input :address, hint: 'Where is your business located?',
                  label: 'Where is your business located? '%>
              <%= f.input :description, hint: 'Explain a little bit about your business',
                  label: 'Tell other bulkers a bit about your business'%>
              <%= f.input :photo, as: :file, hint: 'This will be your avatar',
                  label: 'Avatar' %>
            <%= f.submit :submit, class: 'button btn-filled' %>
          <% end %>
      </div>
    </div>

  </div>

app/views/businesses/edit.html.erb
<%= render 'form' %>

app/views/businesses/new.html.erb
<%= render 'form' %>

app/views/businesses/show.html.erb
<div class="business-info flex">
  <div class="photo">
    <% if  @business.photo.attached? %>
      <%= cl_image_tag @business.photo.key, class: "business-image avatar" %>
    <% else %>
      <%= image_tag "blank-profile-picture-square.png", class: "user-image" %>
    <% end %>
  </div>

    <% if policy(@business).edit? %>
    <%= link_to "Update", edit_business_path(@business), class: "btn btn-empty"%>
    <% end %>

  <div class="content-business">
    <h2>@<%= @business.nickname %></h2>
    <p> <%= @business.description %> </p>
    <div class="line"></div>
    <div class="contact-info">
      <p><i> Contact Information</i></p>
      <p> <%= @business.user.first_name %> <%= @business.user.last_name %></p>
      <p> <%= @business.user.email %> </p>
      <p> <%= @business.address %> </p>
    </div>
  </div>

  <div class="map2">
    <div style="width: 100%; height: 600px;" class="map"
      data-controller="mapbox"
      data-mapbox-marker-value="<%= @marker.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>