config/routes.rb
Rails.application.routes.draw do
  # require "sidekiq/web"
  # authenticate :user, ->(user) { user.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  devise_for :users
  #get '/search', to: 'pages#home', as: :search
  root to: 'pages#home'
 # root to: 'pages#splash'
  # get "/orders/:id/confirmation", to: "orders#confirmation", as: :order_confirmation
  delete "/offers", to: 'offers#destroy_all', as: :destroy_all
  get "/landing", to: 'pages#landing'
  resources :offers do
    resources :comments, only: [ :create ]
    resources :orders, only: [ :create ]
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  resources :businesses, only: [ :show, :new, :create, :edit, :update ]
  resources :orders, only: [ :index, :show, :destroy ] do
    get "/confirmation", to: "orders#confirmation"
    patch "/accept", to: "orders#accept"
    patch "/reject", to: "orders#reject"
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar">
<%= link_to 'javascript:history.back()' do %>
  <%= image_tag "back-icon.png", class:"back-icon" %>
<% end %>
<%= link_to root_path do %>
  <%= image_tag "buythebulk-logo.png", class:"buythebulk-logo" %>
<% end %>
  <%= image_tag "burguer-icon.png", class:"burguer-icon avatar-dropdown-toggle", data: {bs_toggle:"dropdown"}%>
   <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "View offers", offers_path, class: "dropdown-item" %>
              <%# <%= link_to "Profile details", profile_page_path, class: "dropdown-item" %>
              <% if user_signed_in? %>
                <%= link_to "Upload an offer", new_offer_path, class: "dropdown-item" %>
                <%= link_to "My orders", orders_path, class: "dropdown-item" %>
                <% unless current_user.business.present? %>
                <%= link_to "Add my business", new_business_path, class: "dropdown-item" %>
                <% else  %>
                <%= link_to business_path(current_user.business), class: "dropdown-item" do %>
                  <% if current_user.business.photo.key %>
                  <%= cl_image_tag current_user.business.photo.key, class: "avatar-small" %>
                  <% else %>
                  <%= image_tag "avatar.jpg", class:"avatar-small"%>
                  <% end %>
                  <%="#{current_user.business.nickname}" %>
                <% end %>
                <% end %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              <% else %>
                <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
                <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
              <% end %>
            </div>
</div>

app/views/shared/_progress_bar.html.erb
<div class="progress-bar__container">
  <div class="progress-bar-filled" 
    <% if offer.progress_percentage >= 100 %>
      style="background-color: #A4C3B2; transform: translate(100%, 0px);"
    <% else %>
      style="background-color: #CCE3DE; transform: translate(<%= offer.progress_percentage %>%, 0px);"
    <% end %>>
  </div>
</div>