config/routes.rb
Rails.application.routes.draw do
  # require "sidekiq/web"
  # authenticate :user, ->(user) { user.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  devise_for :users
  #get '/search', to: 'pages#home', as: :search
  root to: 'pages#home'
 # root to: 'pages#splash'
  # get "/orders/:id/confirmation", to: "orders#confirmation", as: :order_confirmation
  delete "/offers", to: 'offers#destroy_all', as: :destroy_all
  get "/landing", to: 'pages#landing'
  resources :offers do
    resources :comments, only: [ :create ]
    resources :orders, only: [ :create ]
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  resources :businesses, only: [ :show, :new, :create, :edit, :update ]
  resources :orders, only: [ :index, :show, :destroy ] do
    get "/confirmation", to: "orders#confirmation"
    patch "/accept", to: "orders#accept"
    patch "/reject", to: "orders#reject"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :offer

  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_business, except: :create
  def index
    @orders = policy_scope(Order)
    @orders = Order.joins(:offer).where(user_id:current_user).order("offers.deadline ASC")
    if params[:tab].present?
      @orders = @orders.where("offers.status = '#{params[:tab]}'")
    else
      @orders = @orders.where("offers.status = 'active'")
    end
  end

  def show
    @order = Order.find(params[:id])
    @offer = @order.offer
    @comment = Comment.new
    authorize @order
    @offer = @order.offer
    authorize @offer
    @order.offer = @offer
    participants = []
    @offer.orders.each do |order|
      if order.user != @offer.user
        participants << order.user
      end
    end
    @participants = participants.uniq
  end

  def create
    @offer = Offer.find(params[:offer_id])
    authorize @offer
    @order = Order.new(order_params)
    authorize @offer
    @order.offer = @offer
    @order.user = current_user
    if @order.save!
      redirect_to order_confirmation_path(@order)
    else
      render "offers/show"
    end
  end

  def order_params
    params.require(:order).permit(:amount)
  end

  def confirmation
    @order = Order.find(params[:order_id])
    authorize @order
    @participants = @order.offer.orders.uniq.count

  end

  def destroy
    @order = Order.find(params[:id])
    authorize @order
    @order.destroy
  end

  def accept
    @order = Order.find(params[:order_id])
    authorize @order
    @order.status = 'accepted'
    @order.save
    respond_to do |format|
      format.html { redirect_to order_path(@order) }
      format.json { render json: { expired_buttons: render_to_string(partial: "expired_buttons.html.erb", locals: { order: @order }) } }
    end

  end

  def reject
    @order = Order.find(params[:order_id])
    authorize @order
    @order.status = 'rejected'
    @order.save
    respond_to do |format|
      format.html { redirect_to order_path(@order) }
      format.json { render json: { expired_buttons: render_to_string(partial: "expired_buttons.html.erb", locals: { order: @order }) } }
    end
  end
end

app/views/orders/_expired_buttons.html.erb
<% if order.offer.status == 'expired' && order.status == 'pending' %>
  <div class="target-expired">
    <h5><em>The target was not reached</em></h5>
    <p>Do you want to confirm you order for the initial price?</p>
  </div>
  <div class="expired-buttons">
    <%= link_to "No", order_reject_path(order), class:"button btn-empty btn-expired", data:{ action: "click->expired-decision#reject"}%>
    <%= link_to "Yes", order_accept_path(order), class:"button btn-filled btn-expired", data:{ action: "click->expired-decision#accept"} %>
  </div>
  <% elsif order.offer.status == 'expired' && order.status == 'accepted' %>
  <div class="target-expired">
    <h5><em>The target was not reached</em></h5>
    <p>You have chosen to purchase the products at the initial price.</p>
  </div>
  <div class="expired-decision accepted">
    <div class="button btn-expired-status">Accepted</div>
  </div>
  <% elsif order.offer.status == 'expired' && order.status == 'rejected' %>
  <div class="target-expired">
    <h5><em>The target was not reached</em></h5>
    <p>You have chosen to cancel the order and get a refund.</p>
  </div>
  <div class="expired-decision rejected">
    <div class="button btn-expired-status">Rejected</div>
  </div>
<% end %>

app/views/orders/_orders_cards.html.erb
<div class="orders-card flex">
      <% orders.each do |order| %>
        <%= link_to order_path(order), class:"order-card-link" do %>
          <div class="order-description flex">
            <div class="order-img">
              <% if order.offer.photo.key %>
                <%= cl_image_tag order.offer.photo.key, class: "order-img" %>
              <% else %>
                <%= image_tag "https://cdn.shopify.com/s/files/1/0241/6856/2743/products/2_1296x.png?v=1637265121", class:"order-img"%>
              <% end %>
            </div>
            <div class="order-info">
              <h4><%= order.offer.name %></h4>
              <div>
                <p>Ordered on <%= order.created_at.strftime("%d-%m-%Y") %></p>
                <% if order.offer.status == 'active' %>
                  <p>Offer expires <%= order.offer.days_until_deadline%></p>
                <% else %>
                  <p>Offer expired on <%= order.offer.deadline.strftime("%d-%m-%Y") %></p>
                <% end %>
              </div>
            </div>
            <i class="fas fa-angle-right order-arrow"></i>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/orders/confirmation.html.erb
<div class="container-confirm">
  <div class="header">
    <h2>Congratulations!</h2>
    <p>Your order was successful</p>
  </div>

  <div class="order-summary">
    <h3 class="summary-text">Order Summary</h3>
    <div class="order-box">
      <% if @order.offer.photo.present? %>
        <%= cl_image_tag @order.offer.photo.key, class:"img-confirmation" %>
      <% else %>
        <%= image_tag "https://cdn.shopify.com/s/files/1/0241/6856/2743/products/2_1296x.png?v=1637265121", class:"img-confirmation" %>
      <% end %>
      <div class="order-info">
        <p class="product-name"><%= @order.offer.name %></>
        <div class="order-ordered-info">
          <div class="order-amount">
            <p>Amount</p><p><%= @order.amount %></p>
          </div>
          <div class="order-total">
            <% if @order.offer.target_reached? %>
              <p><strong>Total</strong></p><p><strong>€<%= (@order.amount * @order.offer.target_price).round(2) %></strong></p>
            <% else %>
              <p><strong>Total</strong></p><p><strong>€<%= (@order.amount * @order.offer.initial_price).round(2) %></strong></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="order-progress">
      <div class="offer-card-progress-bar">
        <%= render "shared/progress_bar", offer: @order.offer %>
        <% if @order.offer.target_reached? %>
            <p class="target-reached"> <b>Target reached!</b> </p>
            <% if @participants == 1 %>
              <p class="target-reached">Thanks to you and another bulker we achieved the goal!</p>
            <% else  %>
              <p class="target-reached">Thanks to you and <%= @participants - 1 %> other bulkers we achieved the goal! </p>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div>
    <p class="share-text">Share it with others!</p>
    <div class='share-link' data-controller="clipboard copy-url">
      <input class='form-field-green' type="text" value=<%=offer_url(@order.offer).gsub("www.","")%>  data-clipboard-target="source"/>
      <button type="button" class="button btn-filled btn-clipboard" data-action="clipboard#copy click->copy-url#clicked" data-copy-url-target="button"><i class="fas fa-clipboard clipboard-icon"></i></button>
    </div>
  </div>
  <div class="confirmation-buttons">
    <%= link_to "Keep Browsing", root_path, class: "button btn-filled confirmation-button"%>
    <%= link_to "Dashboard", orders_path, class: "button btn-empty confirmation-button" %>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container">

    <h3 class="header text center">My orders</h3>

    <div class='order-status-tabs'>  
      <%= link_to "Active", orders_path(tab: "active"), class:"button #{params[:tab] == 'active' || !params[:tab].present? ? 'btn-filled' : 'btn-empty'} btn-order-status" , id:"active-orders"%>
      <%= link_to "Accomplished", orders_path(tab: "accomplished"), class: "button #{params[:tab] == 'accomplished' ? 'btn-filled' : 'btn-empty'} btn-order-status", id:"accomplished-orders"%>
      <%= link_to "Expired", orders_path(tab: "expired"), class:"button #{params[:tab] == 'expired' ? 'btn-filled' : 'btn-empty'} btn-order-status", id:"expired-orders"%>
    </div>

    <%= render "orders_cards", orders: @orders %>

</div>

app/views/orders/show.html.erb
<div class="container-show">

  <%# Card with ORDER details %>
  <div class="offer-details">
    <% if @order.offer.photo.key %>
      <%= cl_image_tag @order.offer.photo.key, class: "img-offer-card img-offer-show"%>
    <% else %>
      <div class="od-pic">
        <%= image_tag "https://cdn.shopify.com/s/files/1/0241/6856/2743/products/2_1296x.png?v=1637265121", class:"img-offer-card img-offer-show"%>
      </div>
    <% end %>

    <div class="offer-content">
      <div class="offer-card-progress-bar">
        <%= render "shared/progress_bar", offer: @order.offer %>
      </div>
      <div class="progress-card-details">
        <p><%= @order.offer.ordered_amount %> / <%= @order.offer.target_amount %></p>
        <% if @order.offer.target_reached? %>
          <div class="prices">
            <p>€<%= @order.offer.target_price %></p>
            <p class="lighter-price not-valid-price">€<%= @order.offer.initial_price %></p>
          </div>
        <% else %>
          <div class="prices">
            <p>€<%= @order.offer.initial_price %></p>
            <p class="lighter-price">Target price: €<%= @order.offer.target_price %></p>
          </div>
        <% end %>
      </div>
      <div class="offer-card-details">
        <h1><%= @order.offer.name %></h1>
        <p><%= @order.offer.description %></p>
      </div>
      <div class="offer-card-bottom">
        <% if @order.offer.active? %>
          <p class="offer-deadline"><em>Offer expires <%= @order.offer.days_until_deadline%></em></p>
        <% else %>
          <p class="offer-deadline"><em>This offer expired on <br><%= @order.offer.deadline.strftime("%d-%m-%Y")%></em></p>
        <% end %>
        <div class="offer-category"><%= @order.offer.category %></div>
      </div>
  </div>
</div>
<div class="amount-card">
  <div class="order-show-total">
    <div class="totals">
    <p><strong>Order amount</strong></p>
    <p><%= @order.amount %></p>
    </div>
    <div class="order-show-total" data-controller='expired-decision'>
      <% if @order.offer.target_reached? %>
        <div class="totals">
          <p><strong>Total</strong></p>
          <p>€<%= (@order.amount * @order.offer.target_price).round(2) %></p>
        </div>
        <div class="savings">
          <p><strong>You are saving</strong></p>
          <p>€<%=(@order.amount * (@order.offer.initial_price - @order.offer.target_price)).round(2)%></p>
        </div>
        <div class="green-line"></div>
        <div class="target-expired">
          <h5><em>The target has been reached!</em></h5>
          <% if @order.offer.status == 'accomplished' %>
            <p>The order has automatically been placed and you will receive more information soon.</p>
            <div class="expired-decision accepted">
              <div class="button btn-expired-status">Accepted</div>
            </div>
          <% else %>
            <p>There is still time for other bulkers to join this offer. Share it with others!</p>
            <div class='share-link' data-controller="clipboard copy-url">
              <input class='form-field-green' type="text" value=<%=offer_url(@order.offer).gsub("www.","")%>  data-clipboard-target="source"/>
              <button type="button" class="button btn-filled btn-clipboard" data-action="clipboard#copy click->copy-url#clicked" data-copy-url-target="button"><i class="fas fa-clipboard clipboard-icon"></i></button>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="totals">
          <p><strong>Total</strong></p>
          <p><strong>€<%= (@order.amount * @order.offer.initial_price).round(2) %></strong></p>
        </div>
        <% if @order.offer.status == 'active' %>
          <div class="savings">
            <p>You could be saving</p>
            <p>€<%=(@order.amount * (@order.offer.initial_price - @order.offer.target_price)).round(2)%></p>
          </div>
          <div class="green-line"></div>
          <div class="target-expired">
            <h5><em>The target is not yet reached</em></h5>
            <p>Don't worry, there is still time! Share this offer with others!</p>
              <div class='share-link' data-controller="clipboard copy-url">
                <input class='form-field-green' type="text" value=<%=offer_url(@order.offer).gsub("www.","")%>  data-clipboard-target="source"/>
                <button type="button" class="button btn-filled btn-clipboard" data-action="clipboard#copy click->copy-url#clicked" data-copy-url-target="button"><i class="fas fa-clipboard clipboard-icon"></i></button>
              </div>
          </div>
        <% elsif @order.offer.status == 'expired' %>
          <div class="green-line"></div>
          <div data-expired-decision-target="buttons">
            <%= render 'expired_buttons', order: @order %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<div class="suppliers-info">
  <h2>Supplier Information</h2>
  <h5><%= @order.offer.supplier.name %></h5>
  <a href="<%= @order.offer.supplier_offer_url %>">Supplier's website</a>
</div>

<div class="bulkers-card">
  <div class="bulker-info">
    <div class="info-bu">
      <h5>@<%= @order.offer.user.business.nickname %></h5>
      <p>Is placing this order</p>
    </div>
    <%= link_to business_path(@order.user.business) do %>
      <% if  @order.offer.user.business.photo.attached? %>
        <%= cl_image_tag @order.offer.user.business.photo.key, class: "user-image" %>
      <% else %>
        <%= image_tag "blank-profile-picture-square.png", class: "user-image" %>
      <% end %>
    <% end %>
  </div>
  <div class="bulkers-in">
    <div class="participants-avatars">
      <% @participants.first(3).each do |user| %>
        <%= link_to business_path(user.business) do %>
          <div class="three-users-box">
            <% if user.business.photo.attached? %>
              <%= cl_image_tag user.business.photo.key, class:"three-users"%>
            <% else %>
              <%= image_tag "blank-profile-picture-square.png", class: "three-users" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <% if @participants.count == 1 %>
      <p><%= @participants.count  %> other bulker joined</p>
    <% else %>
      <p><%= @participants.count  %> other bulkers joined</p>
    <% end %>
  </div>
</div>

<%# Comments section %>
<%= render "comments/comment_box" %>