config/routes.rb
Rails.application.routes.draw do
  # require "sidekiq/web"
  # authenticate :user, ->(user) { user.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  devise_for :users
  #get '/search', to: 'pages#home', as: :search
  root to: 'pages#home'
 # root to: 'pages#splash'
  # get "/orders/:id/confirmation", to: "orders#confirmation", as: :order_confirmation
  delete "/offers", to: 'offers#destroy_all', as: :destroy_all
  get "/landing", to: 'pages#landing'
  resources :offers do
    resources :comments, only: [ :create ]
    resources :orders, only: [ :create ]
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  resources :businesses, only: [ :show, :new, :create, :edit, :update ]
  resources :orders, only: [ :index, :show, :destroy ] do
    get "/confirmation", to: "orders#confirmation"
    patch "/accept", to: "orders#accept"
    patch "/reject", to: "orders#reject"
  end
end

app/models/offer.rb
require 'date'

class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :supplier
  has_many :orders, dependent: :delete_all

  has_many :participants, through: :orders, source: :user
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :orders

  has_one_attached :photo
  validates :name, presence: true, length: { minimum: 10 , maximum: 25 }
  validates :description, presence: true, length: { minimum: 50 , maximum: 200 }
  validates :initial_price, presence: true
  validates :target_price, presence: true, numericality: { less_than: :initial_price }
  validates :target_amount, presence: true, numericality: { only_integer: true, greater_than: 1}
  validates :supplier_offer_url, presence: true
  validates :category, presence: true, inclusion: { in: %w(Furniture Textiles Decoration Kitchenware\ &\ Dinnerware Take\ away Pots\ &\ plants Outdoor) }
  validates :deadline, presence: true
  # validate :deadline_cannot_be_in_the_past
  validates :status, inclusion: { in: %w(active accomplished expired expired-accepted expired-rejected)}

  def deadline_cannot_be_in_the_past
    if deadline.present? && deadline < Date.today
      errors.add(:deadline, "can't be in the past")
    end
  end

  def ordered_amount
    orders.reduce(0) { |sum, order| sum + order.amount }
  end

  def days_until_deadline
    days = (deadline.to_datetime - Date.today).to_i
    if days == 1
      return "in #{days} day"
    elsif days == 0
      return "today"
    else
      return "in #{days} days"
    end
  end

  def progress_percentage
    (ordered_amount / target_amount.to_f)*100
  end

  def target_reached?
    ordered_amount >= target_amount
  end

  def active?
    status == "active"
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  skip_before_action :verify_business, except: [:new, :edit, :create ]
  def index
    UpdateOfferStatusJob.perform_now
    if params[:query].present?
      sql_query = 'name ILIKE :query OR description ILIKE :query'
      @offers = policy_scope(Offer).where(sql_query, query: "%#{params[:query]}%").where(status: "active").order(deadline: :asc)
    elsif params[:category].present?
      if params[:category].length > 1
        categories = params[:category].split("-").map { |c| "category ILIKE '#{c}'" }
        sql_query = categories.join(" OR ")
        @offers = policy_scope(Offer).where(sql_query).where(status: "active").order(deadline: :asc)
      elsif params[:category] != "all"
        sql_query = 'category ILIKE :category'
        @offers = policy_scope(Offer).where(sql_query, category: "%#{params[:category]}%").where(status: "active").order(deadline: :asc)
      else
        @offers = policy_scope(Offer).where(status: "active").order(deadline: :asc)
      end
    else
      @offers = policy_scope(Offer).where(status: "active").order(deadline: :asc)
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @comment = Comment.new
    authorize @offer
    @order = Order.new
    authorize @order
    @order.offer = @offer
    participants = []
    @offer.orders.each do |order|
      if order.user != @offer.user
        participants << order.user
      end
    end
    @participants = participants.uniq
    
  end

  def new
    @offer = Offer.new
    authorize @offer
    # @order = Order.new
    # authorize @order

  end

  def create
    @offer = Offer.new(offer_params)
    @order = Order.new(order_params)
    authorize @offer
    authorize @order
    @user = current_user
    @offer.user = @user
    @order.offer = @offer
    @order.user = current_user

    if @offer.save && @order.save
      redirect_to offer_path(@offer), notice: 'Your offer was successfully created! '
    else
      render :new
    end
  end

  def edit
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  def update
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.update(offer_params)

    redirect_to offer_path(@offer)
  end

  def destroy
    @offer = Offer.find(params[:id])
    authorize @offer

    @offer.orders.each do |order|
      authorize order
      order.destroy
    end

    @offer.comments.each do |comment|
      comment.destroy
    end

    redirect_to offers_path
  end

  def destroy_all
    @offers = Offer.all
    @offers.each do |offer|
      offer.orders.each do |order|
        authorize order
        order.destroy
      end
      authorize offer
      offer.comments.each do |comment|
        comment.destroy
      end
      offer.destroy
    end

    redirect_to offers_path
  end

  private

  def offer_params
    params.require(:offer).permit(
      :supplier_offer_url, :supplier_id, :category, :deadline, :photo,
      :name, :description, :initial_price, :target_price,:target_amount, :target_amount)
  end

  def order_params
    params.require(:order).permit(:amount)
  end
end

app/views/offers/_form_offer.html.erb
<% category = %w(furniture textiles decoration kitchenware\ &\ dinnerware take\ away pots\ &\ plants outdoor) %>
<% category.each { |name| name.capitalize!}%>
  <div class="container" data-controller="create-offer-form">
    <div class="row justify-content-center" style="margin-top: 2rem">
      <div class="col-lg-6 col-sm-9 offer-form-view">
          <h1 class="form-title">Create a new offer</h1>
          <%= simple_form_for @offer do |f| %>
            <div class='form-carroussel'>
              <i class="fas fa-chevron-left form-arrow-green hidden" data-create-offer-form-target="back" data-action="click->create-offer-form#back"></i>
              <div class="offer-form">
                <div class="offer-form-section offer-info col-12 active" data-create-offer-form-target="form">
                  <h3>Tell us about the product</h3>
                  <%= f.input :name, hint: 'Remember, being creative can help you out' %>
                  <%= f.input :description, :input_html => {:rows => 5}, hint: 'Provide a detailed description. Example: Size, material, quality...' %>
                  <%= f.input :photo, as: :file, hint: 'Add a clear picture of the product' %>
                </div>
                <div class="offer-form-section offer-targets col-12 hidden" data-create-offer-form-target="form">
                  <h3>What is the saving potential?</h3>
                  <%= f.input :initial_price, html: {class: 'inline-form'}, hint: 'What is the current price/unit' %>
                  <%= f.input :target_price, html: {class: 'inline-form'}, hint: 'What is the desired price/unit' %>
                  <%= f.input :target_amount, hint: 'What is amount of products to reach the desired price?' %>
                  <%= simple_fields_for :order do |f| %>
                    <%= f.input :amount, hint: 'How many will you order now?'%>
                  <% end %>
                </div>
                <div class="offer-form-section offer-supplier-details col-12 hidden" data-create-offer-form-target="form">
                  <h3>Who is the supplier?</h3>
                  <%= f.input :supplier_id, as: :select, include_blank: false, collection: Supplier.all, label_method: :name, hint: 'Please select the supplier from the list'  %>
                  <%= f.input :supplier_offer_url, hint: 'What is the link to the supplier page of the order?' %>
                  <%= f.input :category, as: :select, include_blank: false, collection: category, hint:'Which category suits best?' %>
                  <%= f.input :deadline, as: :string, required: false, input_html: {class: "datepicker"}, placeholder: "yyyy-mm-dd", hint: "What is the final date other Bulkers can join?" %>
                </div>
              </div>
              <i class="fas fa-chevron-right form-arrow-green" data-create-offer-form-target="next" data-action="click->create-offer-form#next"></i>
            </div>
            <div class="dots">
              <i class="fas fa-circle dot active" data-create-offer-form-target="dot"></i>
              <i class="far fa-circle dot" data-create-offer-form-target="dot"></i>
              <i class="far fa-circle dot" data-create-offer-form-target="dot"></i>
            </div>
            <%= f.submit :submit, class: 'button btn-filled btn-offer-form disabled', data: {create_offer_form_target: "submit"}, disabled:true %>
          <% end %>
      </div>
    </div>
  </div>

app/views/offers/edit.html.erb
<%= render 'form_offer' %>

app/views/offers/index.html.erb
<div class="container index-container">
  <div class="search-offer-cards">
    <%= form_with url: offers_path, method: :get, class:"form-row" do |f| %>
      <%= f.text_field :query,
        class: "mb-2 form-field-green form-field-left",
        placeholder: 'Search a specific offer',
        value: params[:query] %>
      <%= f.submit "Search", class: "button btn-filled btn-right" %>
    <% end %>
  </div>

  <% if policy(@offers).destroy_all? %>
  <h2>DANGER ADMIN! THIS WILL DELETE ALL THE SEEDS!!</h2>
  <%= link_to "Delete all", destroy_all_path, method: :delete %>
  <% end %>

  <div class="grid-offer-cards">
    <% @offers.each do |offer| %>
      <% if policy(offer).show? %>
        <div class="offer-card">
          <%= link_to offer_path(offer), class:"card-links" do %>
            <% if offer.photo.key %>
              <%= cl_image_tag offer.photo.key, class: "img-offer-card" %>
            <% else %>
            <%= image_tag "https://cdn.shopify.com/s/files/1/0241/6856/2743/products/2_1296x.png?v=1637265121", class:"img-offer-card"%>
            <% end %>
              <div class="offer-card-progress-bar">
                <%= render "shared/progress_bar", offer: offer %>
              </div>
            <div class="progress-card-details">
              <p><%= offer.ordered_amount %> / <%= offer.target_amount %></p>
              <% if offer.target_reached? %>
                <div class="prices">
                  <p>€<%= offer.target_price %></p>
                  <p class="lighter-price not-valid-price">€<%= offer.initial_price %></p>
                </div>
              <% else %>
                <div class="prices">
                  <p>€<%= offer.initial_price %></p>
                  <p class="lighter-price">Target price: €<%= offer.target_price %></p>
                </div>
              <% end %>
            </div>
            <div class="offer-card-details">
              <h4><%= offer.name %></h4>
              <p><%= truncate(offer.description, :length => 125) %></p>
            </div>
            <div class="offer-card-bottom">
              <p class="offer-deadline"><em>Offer expires <%= offer.days_until_deadline%></em></p>
              <div class="offer-category"><%= offer.category %></div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="upload-offer-section">
    <h4>Not finding what you are looking for?</h6>
    <%= link_to "Upload an offer", new_offer_path, class: 'button btn-empty btn-upload-offer' %>
  </div>
</div>

app/views/offers/new.html.erb
<%= render 'form_offer' %>

app/views/offers/show.html.erb
<% content_for :meta_title, "#{@offer.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @offer.description %>
<% content_for :meta_image, @offer.photo.key ? cl_image_path(@offer.photo.key, width: 256, height: 256, crop: :fill) : image_path('buythebulk-show.png')%>
<% content_for :meta_image_size do %>
  <meta property="og:image:width" content="256" />
  <meta property="og:image:height" content="256" />
<% end %>
<div class="container-show">

<%# Card with OFFER details %>
  <div class="offer-details">
    <% if @offer.photo.key %>
      <div class="od-pic">
        <%= cl_image_tag @offer.photo.key, class: "img-offer-card img-offer-show"%>
        <% if policy(@offer).edit? %>
          <div class="edit-icon">
            <%= link_to edit_offer_path(@offer) do %>
              <i class="fas fa-edit"></i>
             <% end %>
             <%= link_to offer_path(@offer), data: { confirm: "Are you sure?" }, method: :delete do %>
                <i class="fas fa-trash-alt" id="delete-icon"></i>
              <% end %>
          </div>
        <% end %>
      </div>
    <% else %>
    <div class="od-pic">
      <%= image_tag "https://cdn.shopify.com/s/files/1/0241/6856/2743/products/2_1296x.png?v=1637265121", class:"img-offer-card img-offer-show"%>
        <% if policy(@offer).edit? %>
          <div class="edit-icon">
            <%= link_to edit_offer_path(@offer) do %>
              <i class="fas fa-edit"></i>
            <% end %>
            <%= link_to offer_path(@offer), data: { confirm: "Are you sure?" }, method: :delete do %>
                <i class="fas fa-trash-alt" id="delete-icon"></i>
              <% end %>
          </div>
      <% end %>
    </div>
    <% end %>
    <div class="offer-content">
      <div class="offer-card-progress-bar">
        <%= render "shared/progress_bar", offer: @offer %>
      </div>
      <div class="progress-card-details">
        <p><%= @offer.ordered_amount %> / <%= @offer.target_amount %></p>
        <% if @offer.target_reached? %>
          <div class="prices">
            <p>€<%= @offer.target_price %></p>
            <p class="lighter-price not-valid-price">€<%= @offer.initial_price %></p>
          </div>
        <% else %>
          <div class="prices">
            <p>€<%= @offer.initial_price %></p>
            <p class="lighter-price">Target price: €<%= @offer.target_price %></p>
          </div>
        <% end %>
      </div>
      <div class="offer-card-details">
        <h1><%= @offer.name %></h1>
        <p><%= @offer.description %></p>
      </div>
      <div class="offer-card-bottom">
        <% if @offer.active? %>
          <p class="offer-deadline"><em>Offer expires <%= @offer.days_until_deadline%></em></p>
        <% else %>
          <p class="offer-deadline"><em>This offer expired on <br><%= @offer.deadline.strftime("%d-%m-%Y")%></em></p>
        <% end %>
        <div class="offer-category"><%= @offer.category %></div>
      </div>
    </div>

  </div>


<%# Order card with input for amount of products requiered %>
<% if user_signed_in? %>
  <% if @offer.active? %>
    <% if @offer.target_reached? %>
      <div class="amount-card" data-controller="total-price-calc"  data-total-price-calc-unit-price-value="<%= @offer.initial_price %>"data-total-price-calc-current-amount-value="<%= @offer.ordered_amount %>" data-total-price-calc-target-price-value="<%= @offer.target_price %>">
        <%= simple_form_for [ @offer, @order ], data: {action: "change input->total-price-calc#reachedPrice"} do |f| %>
          <p><%= f.input :amount, label: "Order amount", input_html: { data: { total_price_calc_target:"amount" }} %></p>
          <div class="total">
            <p>Total</p>
            <p data-total-price-calc-target="total"><i>0 €</i></p>
          </div>
          <div class="savings">
            <p>You are saving</p>
            <p data-total-price-calc-target="savings"><i></i></p>
          </div>
            <%= f.submit "Order", class: "button btn-filled" %>
          <div class='center-green-line'>
            <div class="green-line"></div>
          </div>
          <div class="target-expired">
            <h5><em>The target has been reached!</em></h5>
            <p>There is still time for other bulkers to join this offer. Share this offer with others!</p>
            <div class='share-link' data-controller="clipboard copy-url">
              <input class='form-field-green' type="text" value=<%=offer_url(@order.offer).gsub("www.","")%>  data-clipboard-target="source"/>
              <button type="button" class="button btn-filled btn-clipboard" data-action="clipboard#copy click->copy-url#clicked" data-copy-url-target="button"><i class="fas fa-clipboard clipboard-icon"></i></button>
            </div>
          </div>
        <% end %>
      </div>
      <% else %>
      <div class="amount-card" data-controller="total-price-calc"  data-total-price-calc-unit-price-value="<%= @offer.initial_price %>" data-total-price-calc-target-amount-value="<%= @offer.target_amount %>" data-total-price-calc-current-amount-value="<%= @offer.ordered_amount %>" data-total-price-calc-target-price-value="<%= @offer.target_price %>">
        <%= simple_form_for [ @offer, @order ], data: {action: "change input->total-price-calc#updatePrice"} do |f| %>
          <p><%= f.input :amount, label: "Order amount", input_html: { data: { total_price_calc_target:"amount" } } %></p>
          <div class="total">
            <p>Total</p>
            <p data-total-price-calc-target="total"><i>0 €</i></p>
          </div>
          <div class="savings">
            <p data-total-price-calc-target="text">You could be saving</p>
            <p data-total-price-calc-target="congratulation"></p>
            <p data-total-price-calc-target="savings"><i>0.00 €</i></p>
          </div>
            <%= f.submit "Order", class: "button btn-filled btn-order" %>
          <div class='center-green-line'>
            <div class="green-line"></div>
          </div>
          <div class="target-expired">
            <h5><em>The target is not yet reached</em></h5>
            <p>Don't worry, there is still time! Share this offer with others!</p>
            <div class='share-link' data-controller="clipboard copy-url">
              <input class='form-field-green' type="text" value=<%=offer_url(@order.offer).gsub("www.","")%>  data-clipboard-target="source"/>
              <button type="button" class="button btn-filled btn-clipboard" data-action="clipboard#copy click->copy-url#clicked" data-copy-url-target="button"><i class="fas fa-clipboard clipboard-icon"></i></button>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="amount-card">
      <p class="order-inactive">You cannot place an order as this offer is no longer active</p>
    </div>
  <% end %>
<% else %>
  <div class="amount-card">
    <p class="order-inactive">Please <%= link_to "Log-in", new_user_session_path %> to place an order.</p>
  </div>
<% end %>
 <div class="suppliers-info">
    <h2>Supplier Information</h2>
    <h5><%= @order.offer.supplier.name %></h5>
    <a href="<%= @order.offer.supplier_offer_url %>">Supplier's website</a>
  </div>
<%# Bulkers-card %>
  <div class="bulkers-card">

    <div class="bulker-info">
      <div class="info-bu">
        <h5>@<%= @offer.user.business.nickname %></h5>
        <p>Is placing this order</p>
      </div>
       <%= link_to business_path(@offer.user.business) do %>
        <% if  @offer.user.business.photo.attached? %>
          <%= cl_image_tag @offer.user.business.photo.key, class: "user-image" %>
        <% else %>
          <%= image_tag "blank-profile-picture-square.png", class: "user-image" %>
        <% end %>
      <% end %>
    </div>
    <% if @participants.nil? %>
        <div class="bulkers-in">
          <p>Be the first bulker to join @<%=@offer.user.business.nickname %>!</p>
        </div>
      <% else  %>
        <div class="bulkers-in">
          <div class="participants-avatars">
          <% @participants.first(3).each do |user| %>
            <%= link_to business_path(user.business) do %>
              <div class="three-users-box">
                <% if user.business.photo.attached? %>
                  <%= cl_image_tag user.business.photo.key, class:"three-users"%>
                <% else %>
                  <%= image_tag "blank-profile-picture-square.png", class: "three-users" %>
                <% end %>
              </div>
            <% end %>
          <% end %>
          </div>
          <% if @participants.count == 1 %>
            <p><%= @participants.count  %> other bulker joined</p>
          <% else %>
            <p><%= @participants.count  %> other bulkers joined</p>
          <% end %>
        </div>
    <% end %>
  </div>

  <%# Comments section %>
  <%= render "comments/comment_box" %>

</div>